export const BASE_URL = `http://localhost:8000`;

export const API_VERSION_1 = `/api/v1`;

export const endPoints = {
	ALL_STUDENTS: `/all-students`,
	ALL_TEACHERS: `/all-teachers`,
	ATTENDANCE_DATA: `/attendance-data`,
	ADMISSION_DATA: `/admission-data`,
	CLASSROOM_DATA: `/classroom-data`,
	EVENTS_DATA: `/events-data`,
	EXAM_DATA: `/exam-data`,
	EXAM_RESULT: `/exam-result`,
	MONTHLY_FEE: `/monthly-fee`,
	PARENT_DATA: `/parent-data`,
	PERIOD_DATA: `/period-data`,
	ROOM_DATA: `/room-data`,
	SECTION_DATA: `/section-data`,
	STUDENT_EVENT_DATA: `/student-event-data`,
	SUBJECT_COURSE_DATA: `/subject-course-data`,
	SPECIFIC_STUDENT: `/specific-student`,
	SPECIFIC_TEACHER: `/specific-teacher`,
	TRANSCRIPT: `/transcript`,
	STUDENT_MARKS_FILTER: `/student-marks-filter`,
	STUDENT_COURSES: `/student-courses`,
	STUDENT_PARTICIPATION: `/student-participations`,
	TEACHER_SECTIONS: `/teacher-teaching-sections`,
	ADD_STUDENT: "/add-student",
	ADD_TEACHER: "/add-teacher",
	ADD_EVENT: "/add-event",
	DELETE_STUDENT: "/delete-student",
	DELETE_TEACHER: "/delete-teacher",
	DELETE_EVENT: "/delete-event",
	UPDATE_STUDENT: "/update-student",
	UPDATE_TEACHER: "/update-teacher",
	UPDATE_EVENT: "/update-event",
	ADMIN_SIGNUP: `/auth/sign-up`,
	ADMIN_SIGIN: `/auth/sign-in`,
};
